// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteHistoryEntry(arg1) {
  return window['go']['main']['App']['DeleteHistoryEntry'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHistoryEntry(arg1) {
  return window['go']['main']['App']['GetHistoryEntry'](arg1);
}

export function HistoryLimit() {
  return window['go']['main']['App']['HistoryLimit']();
}

export function ListHistory() {
  return window['go']['main']['App']['ListHistory']();
}

export function RunDiffTool(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunDiffTool'](arg1, arg2, arg3);
}

export function RunTool(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunTool'](arg1, arg2, arg3);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}
