// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {history} from '../models';

export function ClearHistory():Promise<void>;

export function DeleteHistoryEntry(arg1:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetHistoryEntry(arg1:string):Promise<history.Entry>;

export function HistoryLimit():Promise<number>;

export function ListHistory():Promise<Array<history.Entry>>;

export function RunDiffTool(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RunTool(arg1:string,arg2:string,arg3:Record<string, string>):Promise<string>;

export function SetTheme(arg1:string):Promise<void>;
